spring:
  application:
    name:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: hrpass
    username: hr
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
#  jpa:
#    database-platform: org.hibernate.dialect.Oracle12cDialect
#    hibernate:
#      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always
